on: [push, pull_request]
name: CI

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.21.x, 1.22.x, 1.23.x, 1.24.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
      max-parallel: 3
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Print Go version
        run: go version

      # Linux/macOS 跑 Bash
      - name: Run tests (bash)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          for pkg in $(go list ./...); do
            echo "===> $pkg"
            go test -v -race -short $pkg || exit 1
          done

      # Windows 跑 PowerShell
      - name: Run tests (PowerShell)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $pkgs = go list ./...
          foreach ($pkg in $pkgs) {
            echo "===> $pkg"
            go test -v -race -short $pkg
            if ($LASTEXITCODE -ne 0) { exit 1 }
          }
